# Generated by Django 6.0.4 on 2026-05-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
